LazyTest/Pages/Dashboard.cshtml.cs
using LazyTest.Models;
using LazyTest.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LazyTest.Pages
{
    public class DashboardModel : PageModel
    {
        private readonly ITestingServices _testingServices;

        public DashboardModel(ITestingServices testingServices)
        {
            _testingServices = testingServices;
        }
        public bool NeedPageRefresh { get; set; }
        public List<WebSite> TestSites { get; set; }

        public async Task OnGetAsync()
        {
            TestSites =  await _testingServices.GetTestSitesAsync();
            foreach (var site in TestSites)
            {

                if (site.TestedUrls == 0 || site.IsTesting)
                {
                    if (site.IsTestRunning)
                    {
                        NeedPageRefresh = true;
                    }

                }
            }
            if (TestSites.Any())
                TestSites.Reverse();
           
        }
        public IActionResult OnGetDeleteSite(int id)
        {
           
            _testingServices.DeleteTest(id);
            return RedirectToPage();
        }
    }
}

LazyTest/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace LazyTest.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

LazyTest/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;
using LazyTest.Models;
using LazyTest.Services;

namespace LazyTest.Pages
{
    public class IndexModel : PageModel
    {
   


    }
}

LazyTest/Pages/Integration.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LazyTest.Pages
{
    public class IntegrationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

LazyTest/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LazyTest.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

LazyTest/Pages/TestSite.cshtml.cs
using LazyTest.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using LazyTest.Models;
using System.Text.Json;
using LazyTest.Constants;
using System.Net;
namespace LazyTest.Pages
{
    public class TestSiteModel : PageModel
    {
        private readonly ITestingServices _testingServices;

        public TestSiteModel(ITestingServices testingServices)
        {
            _testingServices = testingServices;
        }
        public string ChartDataJson { get; set; }
        public WebSite TestSite { get; set; }
        public TestResultDisplayModel? TestResultDisplayData { get; set; }
        public TestResultDisplayModel? HighlightData { get; set; }
        public async Task<IActionResult> OnGetAsync(int id)
        {
            TestSite = await _testingServices.GetTestSiteAsync(id);
            if (TestSite==null)
            {
                return NotFound();
            }
            var lastTestSite = await _testingServices.GetLastTest(id);
            var result= await _testingServices.GetResultItems(id);
            var lastTest = await _testingServices.GetLastTest(id);
            TestResultDisplayData= await _testingServices.BuildDisplayModel(TestSite, lastTestSite);
            HighlightData= GetHighlightData();

            if (result == null)
            {
                return NotFound();
            }
           var pieChartData = result.OrderBy(x=>x.HttpStatusCode).GroupBy(x => x.StatusCode).Select(x => new { StatusCode = !string.IsNullOrEmpty(x.Key)? x.Key : "Unknown", Count = x.Count() });
          
           var pieChardLabels = pieChartData.Select(x => x.StatusCode).ToArray();
           var pieChardValues = pieChartData.Select(x => x.Count).ToArray();
           var pieChardColors = result.OrderBy(x => x.HttpStatusCode).GroupBy(x => x.HttpStatusCode).Select(x => ColorByResponseCodeHelper.GetColorNameByCode(x.Key).ToLower()).ToArray();
        var unScanUrls=TestSite.TotalUrls-TestSite.TestedUrls;
        if (unScanUrls > 0)
        {
            pieChardLabels = pieChardLabels.Append("Un scanned Urls").ToArray();
            pieChardValues = pieChardValues.Append(unScanUrls).ToArray();
            pieChardColors = pieChardColors.Append("grey").ToArray();
        }

        var chartData = new
            {
                labels = pieChardLabels,
                datasets = new[]
              {
                    new
                    {   backgroundColor =pieChardColors,
                        data = pieChardValues
                    }
                }
            };
            ChartDataJson = JsonSerializer.Serialize(chartData);

           

            return Page();
        }

        private TestResultDisplayModel? GetHighlightData()
        {
            if (TestResultDisplayData == null)
            {
                return null;
            }
            var highlightData = new TestResultDisplayModel
            {
                SiteMapUrl = TestResultDisplayData.SiteMapUrl,
                TestResultItem = TestResultDisplayData.TestResultItem.Where(x => (x.StatusCode != HttpStatusCode.OK.ToString() && x.StatusCode is not null) || x.ContentLength ==0 || Over10PercentDifference(x.ContentLength,x.LastContentLength)==true ).ToList()
            };
            return highlightData;
        }
        public static bool Over10PercentDifference(long? num1, long? num2)
    {
        if (num1==null || num2 == null ||  num2 == 0 || num1==0 )
        {
            return false;
        }
        // Calculate the absolute difference
        long difference = Math.Abs((long)num1 - (long)num2);

        // Calculate 10% of the larger number
        long largerNumber = Math.Max((long)num1, (long)num2);
        double tenPercent = largerNumber * 0.10;

        // Compare the difference to 10% of the larger number
        return difference > tenPercent;
    }



    }
}

LazyTest/Pages/Dashboard.cshtml
@page
@using LazyTest.Helpers;
@model LazyTest.Pages.DashboardModel
@{
    ViewData["Title"] = "Dashboard page";
}
@if (Model.NeedPageRefresh)
{
    <meta http-equiv="refresh" content="5" />
}

    <table>
        <thead>
            <tr>

                <th>Sitemap Url</th>
                <th></th>
                <th>Date</th>
                <th>Total Urls</th>
                <th>Scanned Urls</th>
                <th>Token</th>
                <th>Running</th>
                <th></th>

            </tr>
        </thead>
        <tbody>
            @foreach (var testSite in Model.TestSites)
            {
                <tr>
                <td><a asp-page="/TestSite" asp-route-id="@testSite.WebsiteId">@testSite.SitemapUrl</a></td>
                <td>&nbsp;&nbsp;&nbsp;</td>
                <td>@TimeZoneHelper.ConvertGmtToSydney(testSite.Created)</td>
                <td>@testSite.TotalUrls</td>
                <td>@testSite.TestedUrls</td>
                <td>@testSite.WebsiteGuid</td>
                <td><div class="@(testSite.IsTestRunning?"loader":"")"></div></td>
                <td><a  asp-page-handler="DeleteSite" asp-route-id="@testSite.WebsiteId">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>

LazyTest/Pages/Index.cshtml
@page
@using LazyTest.Models;
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <div class="row">
        <div class="col-lg-12">
            <div class="input-group">

                <input id="SiteMapUrl" class="form-control" type="url" placeholder="Site map URL or domain (e.g., https://example.com/sitemap.xml)" class="form-control" patten="[Hh][Tt][Tt][Pp][Ss]?:\/\/(?:(?:[a-zA-Z\u00a1-\uffff0-9]+-?)*[a-zA-Z\u00a1-\uffff0-9]+)(?:\.(?:[a-zA-Z\u00a1-\uffff0-9]+-?)*[a-zA-Z\u00a1-\uffff0-9]+)*(?:\.(?:[a-zA-Z\u00a1-\uffff]{2,}))(?::\d{2,5})?(?:\/[^\s]*)?" />
                <span class="input-group-btn">

                    <button type="button" id="startButton" class="btn btn-primary" onclick="runTest()">Run a Test</button>
                    <button type="button" id="runInBackGround" class="btn btn-primary d-none" onclick="runTestInBackGround()">Run in the background</button>
                    <a data-bs-toggle="collapse" class="btn btn-secondary" href="#options" role="button" aria-expanded="false" aria-controls="options">
                        Options
                    </a>
                </span>
            </div><!-- /input-group -->
            <div class="collapse" id="options">
                <div class="col-lg-6">
                    <div class="input-group">
                       
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" id="withdomcount">
                            <label class="form-check-label" for="withdomcount">With DOM count </label>
                        </div>
                    </div>
                    <div class="input-group">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" id="withimages">
                            <label class="form-check-label" for="withimages">With Images </label>
                        </div>
                    </div>

                </div>
            </div>
        </div><!-- /.col-lg-6 -->
    </div>

   

</div>
<div class="row">
    <div class="col-lg-12">
        <div class="d-none progress" style="margin-top:10px;margin-bottom:10px;">
            <div id="progessBar" class="progress-bar" role="progressbar" style="width: 0%;"></div>
        </div>
    </div>

</div>
<a href="" id="reportLink" class="btn btn-primary d-none">Report</a>
<table id="resultTable" class="resultTable d-none" border="1" cellpadding="1" width="100%">
    <thead>
        <tr style="background-color:darkslategray;color:white">
            <td>Url</td>
            <td>Status</td>
            <td>Content length</td>
            <td>DOM count</td>
            <td>Response time (ms)</td>

        </tr>
    </thead>
    <tbody>
        <!-- Table rows will be dynamically added here -->
    </tbody>
</table>

<script>
    var thissiteId = 0;
    var runinbackground = false;
    var currentUrl = "";
    
    async function runTest() {
        const url = document.getElementById("SiteMapUrl").value
        const withImage = document.getElementById("withimages").checked;
        const withdDomcount = document.getElementById("withdomcount").checked;
        if (url != "") {
            await testStarted();
            await testWebsite(url, withdDomcount, withImage);
            await testStopped();
        }
        else {

            alert("Please enter a sitemap url or domain");
        }
    }
     async function runTestInBackGround() {
       
         runinbackground = true;
        const withImage = document.getElementById("withimages").checked;
        const withdDomcount = document.getElementById("withdomcount").checked;
        const url = "/api/runsiteinbackground?itemurl=" + currentUrl + "&siteid=" + thissiteId + "&domcount=" + withdDomcount+"image="+withImage;
        const response = await fetch(url);
        if (response.ok) {
            testStopped();
           

        }
      
    }


    async function testWebsite(sitemapUrl,withDomCount, withImage) {

        setProgessBar(0, 0, "initializing");
        const url = "/api/testsite?image=" + withImage + "&sitemapurl=" + sitemapUrl;
        const response = await fetch(url);
        if (!response.ok) {
            testStopped();
            throw new Error(`Error to get the sitemap of${sitemapUrl}`);

        }
        const data = await response.json();
        const siteid = data.SiteId
        thissiteId = siteid;
        var i = 0;
        for (const element of data.Urls) {
            currentUrl = element;
            if (runinbackground==true)
            {
                break;
            }
            await getData(element, siteid, withDomCount);
            i++;
            setProgessBar(i, data.Urls.length);
        }

    }
    async function getData(itemurl, siteid,withDomCount) {
        const url = "/api/testitem?itemurl=" + itemurl + "&siteid=" + siteid + "&domcount=" + withDomCount;
        try {
            const response = await fetch(url);
            if (!response.ok) {
                console.error(`Response status: ${response.status}`);
            }
            const json = await response.json();
            appendJsonData(json);
        } catch (error) {
            console.error(error.message);

        }
    }
    async function appendJsonData(data) {

        const tableBody = document.getElementById('resultTable').getElementsByTagName('tbody')[0];

        const statusCode = `<span class="${data.StatusCode}">${data.StatusCode}</span>`;
        if (data.StatusCode != data.LastStatusCode) {
            statusCode = `<span class="${data.StatusCode}">${data.StatusCode}</span>/<span class="${data.LastStatusCode}">${data.LastStatusCode}</span>`;
        }

        const contentLength = toKilobytes(data.ContentLength)
        if (data.ContentLength != data.LastContentLength) {
            contentLength += "/" + data.LastContentLength;
        }

        const DOMCount = data.DOMCount;
        if (data.DOMCount != data.LastDOMCount) {
            DOMCount += "/" + data.LastDOMCount;
        }
        const ResponseTime = data.ResponseTime;

        if (data.ResponseTime != data.LastResponseTime) {
            ResponseTime += "/" + data.LastResponseTime;
        }

        var tr = document.createElement('tr');
        tr.innerHTML = '<td><a target="_new" href=' + data.Url + '>' + data.Url + '</a></td>' +
            '<td>' + statusCode + '</td>' +
            '<td align="center">' + contentLength + '</td>' +
            '<td align="certer">' + DOMCount + '</td>' +
            '<td align="certer" >' + Math.floor(ResponseTime) + '</td>';
       // tableBody.appendChild(tr);
        tableBody.insertBefore(tr, tableBody.firstChild);

    }
    async function setProgessBar(now, total) {
        const progressBar = document.getElementById('progessBar');
        if (total == 0) {
            progressBar.parentElement.classList = "initializing";
            
             return;
            
        }
        const percentage = (now / total) * 100;

    progressBar.parentElement.classList = "progress";
        progressBar.style.width = percentage + '%';
        progressBar.textContent = Math.round(percentage) + '%' + ' (' + total + ' items)';
    }
    async function testStarted() {
        const startButton = document.getElementById('startButton');
           const runInBackGround = document.getElementById('runInBackGround');
            runInBackGround.classList = "btn btn-primary";

        startButton.disabled = true; // Disable the button
        const resultTable = document.getElementById('resultTable');
        const tableBody = resultTable.getElementsByTagName('tbody')[0];
        const reportButton = document.getElementById('reportLink');
        reportButton.classList = "d-none";
        tableBody.innerHTML = ''; // Clear all rows in the table body
        resultTable.classList = "resultTable"
        setProgessBar(0, 0)
    }
    async function testStopped() {
        const startButton = document.getElementById('startButton');
        startButton.disabled = false;
        const reportButton = document.getElementById('reportLink');
        reportButton.classList = "btn btn-primary";
        const runInBackGround = document.getElementById('runInBackGround');
        runInBackGround.classList = "d-none";


        reportButton.href = "/testsite?id=" + thissiteId;
    }
   
    function toKilobytes(bytes) {
        if (bytes <= 0) {
            return 0;
        }
        var returnValue = Math.floor(bytes / 1024);
        if (returnValue > 0) {
            return returnValue + " KB";
        }
        else {
            return bytes + " B";
        }
    }

</script>

LazyTest/Pages/Integration.cshtml
@page
@model LazyTest.Pages.IntegrationModel
@{
}
@{
    ViewData["Title"] = "Script Integration";
}
<div class="container mt-4">
    <h1 class="text-center">PowerShell Script Integration</h1>
    <div class="alert alert-info">
        <h4 class="alert-heading">How to Use the PowerShell Script</h4>
        <p>
            1. Download the PowerShell script by clicking the button below.
        </p>
        <p>
            2. Open a PowerShell terminal.
        </p>
        <p>
            3. Navigate to the directory where you saved the script.
        </p>
        <p>
            4. Run the script with the appropriate parameters. Here’s a brief explanation of each parameter:
        </p>
        <ul>
            <li><strong>sitemapUrl:</strong> Can be the URL of a sitemap XML file or just the domain of the website you want to test.</li>
            <li><strong>domcount:</strong> Enables or disables DOM (Document Object Model) counting. Enabling it will take longer as it counts the number of elements on the page.</li>
            <li><strong>image:</strong> Determines whether to scan for images associated with the URLs. Set to <code>true</code> to include image scanning, or <code>false</code> to skip it.</li>
            <li><strong>token:</strong> Used to group tests and track them. This allows you to check the results of the latest test or differentiate between different test scenarios.</li>
        </ul>
        <p>
            Example usage:
        </p>
        <pre><code>.\script.ps1 -image $true -sitemapUrl "https://example.com/sitemap.xml" -domcount $false -token "your_token_here"</code></pre>
        <p>
            Replace the parameter values with the ones you need for your specific test case.
        </p>
    </div>
    <div class="text-center mt-4">
        <a href="~/Scripts/script.ps1" class="btn btn-primary">Download Script</a>
    </div>
</div>

LazyTest/Pages/TestSite.cshtml
@page
@using Extentions;
@model LazyTest.Pages.TestSiteModel
@{
}
<h1>@Model.TestSite.SitemapUrl</h1>

<canvas id="myPieChart" width="400" height="200"></canvas>


<h1 class="display-4">Summary</h1>
@if (Model.HighlightData?.TestResultItem?.Any() ?? false)
{
    <table class="table" border="1" cellpadding="1" width="100%">
        <tr style="background-color:darkslategray;color:white">
            <td>Url</td>
            <td>Status</td>
            <td>Content length</td>
            <td>Dom count</td>
            <td>Response time(Ms)</td>
        </tr>


        @foreach (var testpage in Model.HighlightData.TestResultItem)
        {

            var statusCode = $"<span class=\"{testpage?.StatusCode}\">{testpage?.StatusCode}</span>";
            if (!string.IsNullOrEmpty(testpage?.LastStatusCode) && testpage?.LastStatusCode != testpage?.StatusCode)
            {
                statusCode = $"<span class=\"{testpage?.StatusCode}\">{testpage?.StatusCode}</span>/<span class=\"{testpage?.LastStatusCode}\">{testpage?.LastStatusCode}</span>";
            }
            var contentLength = testpage?.ContentLength.ToKB();
            if (testpage?.LastContentLength > 0 && testpage?.LastContentLength != testpage?.ContentLength)
            {
                contentLength = $"{testpage?.ContentLength.ToKB()}/{testpage?.LastContentLength.ToKB()}";
            }
            var domCount = testpage?.DOMCount.ToString();
            if (testpage?.LastDOMCount > 0 && testpage?.LastDOMCount != testpage?.DOMCount)
            {
                domCount = $"{testpage?.DOMCount}/{testpage?.LastDOMCount}";
            }
            var responseTime = testpage?.ResponseTime.ToString();
            if (testpage?.LastResponseTime > 0 && testpage?.LastResponseTime != testpage?.ResponseTime)
            {
                responseTime = $"{testpage?.ResponseTime}/{testpage?.LastResponseTime}";
            }


            <tr>
                <td style="text-align:left"><a href="@testpage?.Url" target="_blank">@testpage?.Url</a></td>
                <td>@Html.Raw(statusCode)</td>
                <td>@contentLength</td>
                <td>@domCount</td>
                <td>@responseTime</td>
            </tr>

        }


    </table>
}
else
{
    <p>Good job! No highlighted data; the result looks good. Please check the details.</p>

}



<p>
    <a data-bs-toggle="collapse" href="#collapseResult" role="button" aria-expanded="false" aria-controls="collapseResult">
        Show Detail Result
    </a>
</p>
<div class="collapse" id="collapseResult">
    <div class="card card-body">
        <h1 class="display-4">Result</h1>
        @if (Model.TestResultDisplayData?.TestResultItem?.Any() ?? false)
        {
            <table class="table" border="1" cellpadding="1" width="100%">
                <tr style="background-color:darkslategray;color:white">
                    <td>Url</td>
                    <td>Status</td>
                    <td>Content length</td>
                    <td>Dom count</td>
                    <td>Response time(Ms)</td>
                </tr>

          
                @foreach (var testpage in Model.TestResultDisplayData.TestResultItem)
                {

                    var statusCode = $"<span class=\"{testpage?.StatusCode}\">{testpage?.StatusCode}</span>";
                    if (!string.IsNullOrEmpty(testpage?.LastStatusCode) && testpage?.LastStatusCode != testpage?.StatusCode)
                    {
                        statusCode = $"<span class=\"{testpage?.StatusCode}\">{testpage?.StatusCode}</span>/<span class=\"{testpage?.LastStatusCode}\">{testpage?.LastStatusCode}</span>";
                    }
                    var contentLength = testpage?.ContentLength.ToKB();
                    if (testpage?.LastContentLength > 0 && testpage?.LastContentLength != testpage?.ContentLength)
                    {
                        contentLength = $"{testpage?.ContentLength.ToKB()}/{testpage?.LastContentLength.ToKB()}";
                    }
                    var domCount = testpage?.DOMCount.ToString();
                    if (testpage?.LastDOMCount>0 && testpage?.LastDOMCount != testpage?.DOMCount)
                    {
                        domCount = $"{testpage?.DOMCount}/{testpage?.LastDOMCount}";
                    }
                    var responseTime = testpage?.ResponseTime.ToString();
                    if (testpage?.LastResponseTime >0 && testpage?.LastResponseTime != testpage?.ResponseTime)
                    {
                        responseTime = $"{testpage?.ResponseTime}/{testpage?.LastResponseTime}";
                    }


                    <tr>
                        <td style="text-align:left"><a href="@testpage?.Url" target="_blank">@testpage?.Url</a></td>
                        <td>@Html.Raw(statusCode)</td>
                        <td>@contentLength</td>
                        <td>@domCount</td>
                        <td>@responseTime</td>
                    </tr>

                }
                
           
            </table>
        }
        
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var ctx = document.getElementById('myPieChart').getContext('2d');
        var chartData = @Html.Raw(Model.ChartDataJson);

        var myPieChart = new Chart(ctx, {
            type: 'pie',
            data: chartData,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    tooltip: {
                        callbacks: {
                            label: function (tooltipItem) {
                                return tooltipItem.label + ': ' + tooltipItem.raw;
                            }
                        }
                    }
                }
            }
        });
    });
</script>